version: "2"
services:
  proxy:
    build:
      context: .
    ports:
      - "5001:5000"
    depends_on:
      - downstream-dotnet-core
      - downstream-python
    environment:
      - OTLP_HTTP_TARGET=http://gateway:4318
      - DOWNSTREAM_PYTHON_TARGET=http://downstream-python:5000/sample
      - DOWNSTREAM_DOTNET_TARGET=http://downstream-dotnet-core:8080/weatherforecast
      - FLASK_APP=proxy
  downstream-python:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - agent
    environment:
      - OTLP_TARGET=http://agent:4317
      - FLASK_APP=app
  downstream-dotnet-core:
    build: 
      context: ./dotnet-core/
    environment:
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://agent:4318/v1/traces
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - agent
  agent:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-config.yaml", "--log-level=INFO"]
    ports:
      - "8888:8888"      
      - "13133:13133"
      - "55679:55679"
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-config.yaml
    depends_on: 
      - gateway
  gateway:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-config.yaml", "--log-level=DEBUG"]
    ports:
      - "7134:7134"
      - "8889:8888"
      - "13134:13133"
      - "55680:55679"
    volumes:
      - ./otel-gateway-config.yaml:/etc/otel-config.yaml
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one
    command: ["--log-level=ERROR"]
    ports:
      - "16686:16686"
