extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  attributes:
    actions:
      - key: tenant
        value: gateway
        action: insert
  batch:
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  logging:
    logLevel: debug
service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes, batch]
      exporters: [jaeger, logging]