extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
processors:
  attributes:
    actions:
      - key: environment
        value: dev
        action: insert
  batch:
exporters:
  otlp:
    # Send gRPC data to the gateway on a custom port
    # since we have a port conflict for gRPC data due
    # to running two collectors on the same network    
    endpoint: gateway:7134
    insecure: true
  logging:
    logLevel: debug

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp, logging]