extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  attributes:
    actions:
      - key: environment
        value: dev
        action: insert
  batch:
exporters:
  otlp:
    endpoint: gateway:4320
    insecure: true
  logging:
    logLevel: debug

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp, logging]
