---
name: Terraform security scan

on:
  pull_request:

jobs:
  tfsec-sarif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          working_directory: infra/
          github_token: ${{ github.token }}

