---
name: tfsec-sarif

on:
  push:
  pull_request:

jobs:
  tfsec-sarif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: tfsec
        uses: tfsec/tfsec-sarif-action@main
        with:
          working_directory: infra/
          sarif_file: tfsec.sarif
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
